name: development Pipeline

# Execution needs to be triggered manually at https://github.com/BetterDiscord/Installer/actions/workflows/development-pipeline.yml.

# This pipeline is pretty hard-coded and will deliver
# identical results no matter the branch it's run against.

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: The version label to be used for this development
        required: true

concurrency: development

jobs:

  # Checkout 'development', merge 'development', bump version, upload source artifact.
  prepare:
    name: Prepare Repo
    runs-on: ubuntu-latest
    outputs:
      old_version: ${{ steps.version_bump.outputs.old_version }}
      new_version: ${{ steps.version_bump.outputs.new_version }}
    steps:

      - name: checkout 'development'
        uses: actions/checkout@v4
        with:
          ref: 'development'
          fetch-depth: 0

      - uses: actions/upload-artifact@v4
        with:
          name: source
          path: |
            ./*
            !.git/config

  # Download source artifact, build, upload build artifact.
  # Runs once on each development platform.
  build:
    name: Build
    needs: prepare
    strategy:
      fail-fast: true
      matrix:
        os:
          # ordered by how fast they build (muh cosmetics)
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/download-artifact@v4
        with:
          name: source

      - run: yarn install && yarn dist
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

      - uses: actions/upload-artifact@v4
        if: ${{ success() && matrix.os == 'ubuntu-latest' }}
        with:
          name: build
          path: dist/BetterDiscord-Linux.AppImage
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        if: ${{ success() && matrix.os == 'windows-latest' }}
        with:
          name: build
          path: dist/BetterDiscord-Windows.exe
          if-no-files-found: error

      - if: ${{ success() && matrix.os == 'macos-latest' }}
        run: mv -f dist/BetterDiscord-*-mac.zip dist/BetterDiscord-Mac.zip
      - if: ${{ success() && matrix.os == 'macos-latest' }}
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/BetterDiscord-Mac.zip
          if-no-files-found: error

  # Download source artifact, push to 'development'.
  push_changes:
    name: Push Version Bump
    needs:
      - prepare
      - build
    runs-on: ubuntu-latest
    outputs:
      sha_1: ${{ steps.push.outputs.sha_1 }}
    steps:

      - name: checkout 'development'
        uses: actions/checkout@v4
        with:
          ref: 'development'
          token: ${{ secrets.CI_PAT }}
          clean: false
      - uses: actions/download-artifact@v4
        with:
          name: source

      - name: merge 'development' and push everything
        id: push
        run: |
          git checkout 'development'
          git config --global user.name "BetterDiscord CI"
          git config --global user.email "BetterDiscord@users.noreply.github.com"
          # TODO: rebase 'development' on 'development'
          git merge --ff-only --no-commit 'development'
          SHA1=$(git rev-parse --verify HEAD)
          git tag "$NEW_VERSION" "$SHA1"
          git push --all && git push --tags
          echo "::set-output name=sha_1::$SHA1"
        env:
          NEW_VERSION: ${{ needs.prepare.outputs.new_version }}

  # Download build artifact, do github development.
  publish:
    name: Draft development
    needs:
      - prepare
      - build
      - push_changes
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.push_changes.outputs.sha_1 }}

      - name: authenticate gh-cli
        run: echo "$GITHUB_TOKEN_STUPIDO" | gh auth login --with-token
        env:
          GITHUB_TOKEN_STUPIDO: ${{ secrets.CI_PAT }}

      - uses: actions/download-artifact@v4
        with:
          name: build

      - name: upload development draft
        run: |
          gh development create "$NEW_VERSION" --draft --title "$NEW_VERSION" --target "$SHA1" --generate-notes \
            "BetterDiscord-Linux.AppImage#Linux (AppImage)" \
            "BetterDiscord-Mac.zip#Mac OS (Zip)" \
            "BetterDiscord-Windows.exe#Windows (Exe)"
        env:
          SHA1: ${{ needs.push_changes.outputs.sha_1 }}
          OLD_VERSION: ${{ needs.prepare.outputs.old_version }}
          NEW_VERSION: ${{ needs.prepare.outputs.new_version }}
          NAKED_INPUT_VERSION_TAG: ${{ github.event.inputs.version_tag }}
          development_NOTES_TEMPLATE_LOCATION: .github/development_TEMPLATE.md
